spring.application.name=argus-intelligence-api
server.port=8080

# Oracle FIAP
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521/ORCL
spring.datasource.username=rm561052
spring.datasource.password=280798
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.sql.init.mode=never

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# NASA FIRMS - externa
nasa.firms.map-key=e37c223808f6067a760b3de8d9443d79
nasa.firms.base-url=https://firms.modaps.eosdis.nasa.gov/api
nasa.firms.source=VIIRS_SNPP_NRT
nasa.firms.area=-85,-57,-32,14
nasa.firms.day-range=1

# APIs locais
ia.api.url=http://localhost:8082
csharp.api.url=http://localhost:8081

# Weather externa
weather.api.url=https://api.open-meteo.com/v1/forecast

# Feign
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=10000

# Cache
spring.cache.type=simple

# RabbitMQ local
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Desliga Azure OpenAI por enquanto
spring.ai.azure.openai.endpoint=http://localhost:9999
spring.ai.azure.openai.api-key=fake-key
spring.ai.azure.openai.chat.options.deployment-name=fake-deployment